Quality of life shit
Darker-Ink/DBH-Rewrite pull request #7
Opened 2022-09-18 09:03 UTC by James-Discord

james doesnt know how to code :(

2022-09-18 09:06 UTC, Darker-Ink requested changes

2022-09-18 09:06 UTC, Darker-Ink commented on src/commands/server/create.js
> +        error: "The commands for this server are disabled!"
The command category is server thats why its like that

2022-09-18 11:48 UTC, Darker-Ink requested changes

2022-09-18 11:48 UTC, Darker-Ink commented on src/commands/server/create.js
> +        error: "The commands for this server are disabled!"
@James-Discord Fix this and I'll merge it

2022-09-18 11:49 UTC, Darker-Ink commented on src/commands/server/create.js
> +        error: "The commands for this server are disabled!"
@James-Discord Fix this and I'll merge it

2022-09-26 15:22 UTC, Darker-Ink commented
Closing since been ignored

2022-09-26 15:22 UTC, closed without merging

2022-09-26 20:42 UTC, James-Discord reviewed
g